[build-system]
requires = [
    "setuptools>=61.0", 
    "aiohttp>=3.9.0",
    "python-dotenv==1.0.0",
    "tiktoken>=0.5.1",
    "pydantic>=2.6.0",
    "cryptography>=42.0.0",
    "aiocache==0.12.2",
    "pandas>=2.1.0"
]
build-backend = "setuptools.build_meta"

[project]
name="lionagi"
authors=[{name = "Haiyang Li", email="ocean@lionagi.ai"}]
description="Towards automated general intelligence."
dynamic = ["version"]
readme = "README.md"
requires-python = ">= 3.9"
dependencies = [
    "aiohttp>=3.9.0",
    "python-dotenv==1.0.0",
    "tiktoken>=0.5.1",
    "pydantic>=2.6.0",
    "cryptography>=42.0.0",
    "aiocache==0.12.2",
    "pandas>=2.1.0"
]
license = {file = "LICENSE"}
classifiers=[
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]

[project.urls]
PyPI = "https://pypi.org/project/lionagi/"
Repository = "https://github.com/lion-agi/lionagi"
Discord = "https://discord.gg/ACnynvvPjt"
