license = {file = "LICENSE"}
classifiers=[
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]

[tool.poetry]
name = "lionagi"
version = "0.3.8"
description = "Towards automated general intelligence."
authors = ["HaiyangLi <quantocean.li@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
aiocache = "^0.12.0"
ipython = "^8.0.0"
lion-core = "^0.5.6"
python-dotenv = "^1.0.1"

[tool.poetry.group.dev.dependencies]
isort = "^5.13.2"
setuptools = "^75.1.0"
pytest = "^8.3.3"
pre-commit = "^4.0.0"
pytest-asyncio = "^0.24.0"
black = {extras = ["jupyter"], version = "^24.8.0"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 79
target-version = ['py310']

[tool.isort]
profile = "black"
line_length = 79

[tool.flake8]
ignore = ["E203", "W503", "E501", "E402"]
max-line-length = 79
exclude = [".git", "__pycache__", "build", "dist", ".venv"]
